site_name: My Docs

theme:
  name: material
  features:
    - content.tabs.link

markdown_extensions: 
  # - pymdownx.highlight
  # - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
